events { worker_connections 1024; }
http {
    upstream flask_app {
        server 127.0.0.1:8080;
    }
    server {
        listen 80;
        
        # Heavy Traffic & DDoS Protection Limits (Correct Place)
        client_max_body_size 1m;

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
